# Generated by Django 4.2.4 on 2024-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование проекта')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('date', models.DateField(verbose_name='Дата проекта')),
                ('description', models.TextField()),
            ],
        ),
    ]
