# Generated by Django 4.2.4 on 2024-09-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование проекта')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('client', models.CharField(max_length=256, null=True, verbose_name='Заказчик')),
                ('category', models.CharField(choices=[('industry', 'Промышленность'), ('logistics', 'Логистика'), ('warehouses', 'Склады'), ('public-objects', 'Общественные объекты'), ('other', 'Другие')], default='industry', max_length=50, verbose_name='Категория')),
                ('date', models.DateField(verbose_name='Дата проекта')),
                ('area', models.IntegerField(null=True, verbose_name='Площадь')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.project')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
