# Generated by Django 4.2.4 on 2024-09-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_projectimage_hero_carusel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='hero_carusel',
            new_name='hero_carousel',
        ),
    ]
