# Generated by Django 4.2.4 on 2024-09-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_project_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('reconstruction', 'Реконструкция'), ('general_design', 'Генпроектирование'), ('p-stage', 'Стадия "П"'), ('r-stage', 'Стадия "Р"')], default='reconstruction', max_length=50),
        ),
    ]
