# Generated by Django 4.2.4 on 2024-09-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('reconstruction', 'Реконструкция'), ('general-design', 'Генпроектирование'), ('p-stage', 'Стадия "П"'), ('r-stage', 'Стадия "Р"')], default='reconstruction', max_length=50),
        ),
    ]
