# Generated by Django 4.2.4 on 2024-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('industry', 'Промышленность'), ('logistics', 'Логистика'), ('warehouses', 'Склады'), ('public-objects', 'Общественные объекты'), ('other', 'Другие')], default='industry', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
    ]
